sudo: required
services:
  - docker
before_install:
  - docker build -t auxility/url-shortener .
script:
  - docker images auxility/url-shortener
deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push auxility/url-shortener
  on:
    branch: master